### ISSUE TITLE
Cats3 + Scala2 supported.

### ISSUE THREAD

**Issue by djx314** [ThoughtWorksInc/dsl-domains-cats#77]
Due to some problem for cats-effect-cps support for scala2. Can dsl-domain-cats update to cats3 for the current support?

Ref https://github.com/typelevel/cats-effect-cps/issues/77

**Comment by Atry** [comment]
What is Cats3?

**Comment by djx314** [comment]
Oh, sorry for the terrible mistake.

Is `dsl-domains-cats` supported `cats-effect3`?

**Comment by Atry** [comment]
Why not?

水山清风 ***@***.***>于2022年7月10日 周日下午1:43写道：

**Comment by djx314** [comment]
That's perfect.

**Comment by djx314** [comment]
Close since it's a misunderstanding.
